//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCJobSearch
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_Table
    {
        public int App_ID { get; set; }
        public int User_ID { get; set; }
        public int Comp_ID { get; set; }
        public int Job_ID { get; set; }
        public string CV { get; set; }
        public System.DateTime App_Date { get; set; }
        public int App_Status { get; set; }
    }
}
