//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCJobSearch
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_Reg
    {
        public int Comp_ID { get; set; }
        public string Comp_Name { get; set; }
        public string Comp_Address { get; set; }
        public string Comp_Phone { get; set; }
        public string Comp_Website { get; set; }
    }
}
