//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCJobSearch
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_Table
    {
        public int Job_ID { get; set; }
        public int Comp_ID { get; set; }
        public string Job_Title { get; set; }
        public string Job_Exp { get; set; }
        public string Job_Skills { get; set; }
        public int Job_Vacancy { get; set; }
        public System.DateTime Date { get; set; }
        public int Job_Status { get; set; }
    }
}
