//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCJobSearch
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Vault2Entities : DbContext
    {
        public Vault2Entities()
            : base("name=Vault2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<App_Table> App_Table { get; set; }
        public virtual DbSet<Company_Reg> Company_Reg { get; set; }
        public virtual DbSet<Job_Table> Job_Table { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<User_Reg> User_Reg { get; set; }
    
        public virtual ObjectResult<SP_AllUserData_Result> SP_AllUserData(Nullable<System.DateTime> dat)
        {
            var datParameter = dat.HasValue ?
                new ObjectParameter("dat", dat) :
                new ObjectParameter("dat", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_AllUserData_Result>("SP_AllUserData", datParameter);
        }
    
        public virtual int SP_ApplicationInsert(Nullable<int> uid, Nullable<int> cid, Nullable<int> jid, string cv, Nullable<System.DateTime> dat, Nullable<int> stat)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var cidParameter = cid.HasValue ?
                new ObjectParameter("cid", cid) :
                new ObjectParameter("cid", typeof(int));
    
            var jidParameter = jid.HasValue ?
                new ObjectParameter("jid", jid) :
                new ObjectParameter("jid", typeof(int));
    
            var cvParameter = cv != null ?
                new ObjectParameter("cv", cv) :
                new ObjectParameter("cv", typeof(string));
    
            var datParameter = dat.HasValue ?
                new ObjectParameter("dat", dat) :
                new ObjectParameter("dat", typeof(System.DateTime));
    
            var statParameter = stat.HasValue ?
                new ObjectParameter("stat", stat) :
                new ObjectParameter("stat", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ApplicationInsert", uidParameter, cidParameter, jidParameter, cvParameter, datParameter, statParameter);
        }
    
        public virtual int SP_CompanyRegistration(Nullable<int> id, string na, string addr, string ph, string web)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var naParameter = na != null ?
                new ObjectParameter("na", na) :
                new ObjectParameter("na", typeof(string));
    
            var addrParameter = addr != null ?
                new ObjectParameter("addr", addr) :
                new ObjectParameter("addr", typeof(string));
    
            var phParameter = ph != null ?
                new ObjectParameter("ph", ph) :
                new ObjectParameter("ph", typeof(string));
    
            var webParameter = web != null ?
                new ObjectParameter("web", web) :
                new ObjectParameter("web", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CompanyRegistration", idParameter, naParameter, addrParameter, phParameter, webParameter);
        }
    
        public virtual int SP_JobInsert(Nullable<int> cid, string jtitle, string exp, string skill, Nullable<int> va, Nullable<System.DateTime> dat, Nullable<int> stat)
        {
            var cidParameter = cid.HasValue ?
                new ObjectParameter("cid", cid) :
                new ObjectParameter("cid", typeof(int));
    
            var jtitleParameter = jtitle != null ?
                new ObjectParameter("jtitle", jtitle) :
                new ObjectParameter("jtitle", typeof(string));
    
            var expParameter = exp != null ?
                new ObjectParameter("exp", exp) :
                new ObjectParameter("exp", typeof(string));
    
            var skillParameter = skill != null ?
                new ObjectParameter("skill", skill) :
                new ObjectParameter("skill", typeof(string));
    
            var vaParameter = va.HasValue ?
                new ObjectParameter("va", va) :
                new ObjectParameter("va", typeof(int));
    
            var datParameter = dat.HasValue ?
                new ObjectParameter("dat", dat) :
                new ObjectParameter("dat", typeof(System.DateTime));
    
            var statParameter = stat.HasValue ?
                new ObjectParameter("stat", stat) :
                new ObjectParameter("stat", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_JobInsert", cidParameter, jtitleParameter, expParameter, skillParameter, vaParameter, datParameter, statParameter);
        }
    
        public virtual ObjectResult<SP_JobResults_Result> SP_JobResults(Nullable<System.DateTime> dat, string s1, string s2, string s3)
        {
            var datParameter = dat.HasValue ?
                new ObjectParameter("dat", dat) :
                new ObjectParameter("dat", typeof(System.DateTime));
    
            var s1Parameter = s1 != null ?
                new ObjectParameter("s1", s1) :
                new ObjectParameter("s1", typeof(string));
    
            var s2Parameter = s2 != null ?
                new ObjectParameter("s2", s2) :
                new ObjectParameter("s2", typeof(string));
    
            var s3Parameter = s3 != null ?
                new ObjectParameter("s3", s3) :
                new ObjectParameter("s3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_JobResults_Result>("SP_JobResults", datParameter, s1Parameter, s2Parameter, s3Parameter);
        }
    
        public virtual int SP_JobSearchQry(string qry)
        {
            var qryParameter = qry != null ?
                new ObjectParameter("qry", qry) :
                new ObjectParameter("qry", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_JobSearchQry", qryParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_LoginCount(string na, string pw)
        {
            var naParameter = na != null ?
                new ObjectParameter("na", na) :
                new ObjectParameter("na", typeof(string));
    
            var pwParameter = pw != null ?
                new ObjectParameter("pw", pw) :
                new ObjectParameter("pw", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_LoginCount", naParameter, pwParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_LoginIDGet(string na, string pw)
        {
            var naParameter = na != null ?
                new ObjectParameter("na", na) :
                new ObjectParameter("na", typeof(string));
    
            var pwParameter = pw != null ?
                new ObjectParameter("pw", pw) :
                new ObjectParameter("pw", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_LoginIDGet", naParameter, pwParameter);
        }
    
        public virtual int SP_LoginInsert(Nullable<int> rid, string una, string pwd, string stat)
        {
            var ridParameter = rid.HasValue ?
                new ObjectParameter("rid", rid) :
                new ObjectParameter("rid", typeof(int));
    
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            var statParameter = stat != null ?
                new ObjectParameter("stat", stat) :
                new ObjectParameter("stat", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_LoginInsert", ridParameter, unaParameter, pwdParameter, statParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_LoginMaxCount()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_LoginMaxCount");
        }
    
        public virtual ObjectResult<string> SP_LogType(string na, string pw)
        {
            var naParameter = na != null ?
                new ObjectParameter("na", na) :
                new ObjectParameter("na", typeof(string));
    
            var pwParameter = pw != null ?
                new ObjectParameter("pw", pw) :
                new ObjectParameter("pw", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_LogType", naParameter, pwParameter);
        }
    
        public virtual ObjectResult<SP_UserDataS1_Result> SP_UserDataS1(Nullable<System.DateTime> dat, string s1)
        {
            var datParameter = dat.HasValue ?
                new ObjectParameter("dat", dat) :
                new ObjectParameter("dat", typeof(System.DateTime));
    
            var s1Parameter = s1 != null ?
                new ObjectParameter("s1", s1) :
                new ObjectParameter("s1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_UserDataS1_Result>("SP_UserDataS1", datParameter, s1Parameter);
        }
    
        public virtual ObjectResult<SP_UserDataS2_Result> SP_UserDataS2(Nullable<System.DateTime> dat, string s1, string s2)
        {
            var datParameter = dat.HasValue ?
                new ObjectParameter("dat", dat) :
                new ObjectParameter("dat", typeof(System.DateTime));
    
            var s1Parameter = s1 != null ?
                new ObjectParameter("s1", s1) :
                new ObjectParameter("s1", typeof(string));
    
            var s2Parameter = s2 != null ?
                new ObjectParameter("s2", s2) :
                new ObjectParameter("s2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_UserDataS2_Result>("SP_UserDataS2", datParameter, s1Parameter, s2Parameter);
        }
    
        public virtual ObjectResult<SP_UserDataS3_Result> SP_UserDataS3(Nullable<System.DateTime> dat, string s1, string s2, string s3)
        {
            var datParameter = dat.HasValue ?
                new ObjectParameter("dat", dat) :
                new ObjectParameter("dat", typeof(System.DateTime));
    
            var s1Parameter = s1 != null ?
                new ObjectParameter("s1", s1) :
                new ObjectParameter("s1", typeof(string));
    
            var s2Parameter = s2 != null ?
                new ObjectParameter("s2", s2) :
                new ObjectParameter("s2", typeof(string));
    
            var s3Parameter = s3 != null ?
                new ObjectParameter("s3", s3) :
                new ObjectParameter("s3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_UserDataS3_Result>("SP_UserDataS3", datParameter, s1Parameter, s2Parameter, s3Parameter);
        }
    
        public virtual ObjectResult<SP_UserDataS4_Result> SP_UserDataS4(Nullable<System.DateTime> dat, string s1)
        {
            var datParameter = dat.HasValue ?
                new ObjectParameter("dat", dat) :
                new ObjectParameter("dat", typeof(System.DateTime));
    
            var s1Parameter = s1 != null ?
                new ObjectParameter("s1", s1) :
                new ObjectParameter("s1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_UserDataS4_Result>("SP_UserDataS4", datParameter, s1Parameter);
        }
    
        public virtual ObjectResult<SP_UserDataS5_Result> SP_UserDataS5(Nullable<System.DateTime> dat, string s1)
        {
            var datParameter = dat.HasValue ?
                new ObjectParameter("dat", dat) :
                new ObjectParameter("dat", typeof(System.DateTime));
    
            var s1Parameter = s1 != null ?
                new ObjectParameter("s1", s1) :
                new ObjectParameter("s1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_UserDataS5_Result>("SP_UserDataS5", datParameter, s1Parameter);
        }
    
        public virtual ObjectResult<SP_UserDataS6_Result> SP_UserDataS6(Nullable<System.DateTime> dat, string s1, string s2)
        {
            var datParameter = dat.HasValue ?
                new ObjectParameter("dat", dat) :
                new ObjectParameter("dat", typeof(System.DateTime));
    
            var s1Parameter = s1 != null ?
                new ObjectParameter("s1", s1) :
                new ObjectParameter("s1", typeof(string));
    
            var s2Parameter = s2 != null ?
                new ObjectParameter("s2", s2) :
                new ObjectParameter("s2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_UserDataS6_Result>("SP_UserDataS6", datParameter, s1Parameter, s2Parameter);
        }
    
        public virtual ObjectResult<SP_UserDataS7_Result> SP_UserDataS7(Nullable<System.DateTime> dat, string s1, string s2)
        {
            var datParameter = dat.HasValue ?
                new ObjectParameter("dat", dat) :
                new ObjectParameter("dat", typeof(System.DateTime));
    
            var s1Parameter = s1 != null ?
                new ObjectParameter("s1", s1) :
                new ObjectParameter("s1", typeof(string));
    
            var s2Parameter = s2 != null ?
                new ObjectParameter("s2", s2) :
                new ObjectParameter("s2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_UserDataS7_Result>("SP_UserDataS7", datParameter, s1Parameter, s2Parameter);
        }
    
        public virtual int SP_UserRegistration(Nullable<int> id, string na, Nullable<int> ag, string addr, string ph, string em, string gen, string qual, Nullable<int> exp, string skill, string img, string cv)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var naParameter = na != null ?
                new ObjectParameter("na", na) :
                new ObjectParameter("na", typeof(string));
    
            var agParameter = ag.HasValue ?
                new ObjectParameter("ag", ag) :
                new ObjectParameter("ag", typeof(int));
    
            var addrParameter = addr != null ?
                new ObjectParameter("addr", addr) :
                new ObjectParameter("addr", typeof(string));
    
            var phParameter = ph != null ?
                new ObjectParameter("ph", ph) :
                new ObjectParameter("ph", typeof(string));
    
            var emParameter = em != null ?
                new ObjectParameter("em", em) :
                new ObjectParameter("em", typeof(string));
    
            var genParameter = gen != null ?
                new ObjectParameter("gen", gen) :
                new ObjectParameter("gen", typeof(string));
    
            var qualParameter = qual != null ?
                new ObjectParameter("qual", qual) :
                new ObjectParameter("qual", typeof(string));
    
            var expParameter = exp.HasValue ?
                new ObjectParameter("exp", exp) :
                new ObjectParameter("exp", typeof(int));
    
            var skillParameter = skill != null ?
                new ObjectParameter("skill", skill) :
                new ObjectParameter("skill", typeof(string));
    
            var imgParameter = img != null ?
                new ObjectParameter("img", img) :
                new ObjectParameter("img", typeof(string));
    
            var cvParameter = cv != null ?
                new ObjectParameter("cv", cv) :
                new ObjectParameter("cv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UserRegistration", idParameter, naParameter, agParameter, addrParameter, phParameter, emParameter, genParameter, qualParameter, expParameter, skillParameter, imgParameter, cvParameter);
        }
    
        public virtual ObjectResult<string> SP_GetCVDetails(Nullable<int> uid)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_GetCVDetails", uidParameter);
        }
    }
}
